services:
  mongodb:
    image: mongo:latest
    container_name: student-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongodbdata:/data/db
    environment:
      - MONGO_INITDB_DATABASE=student_management
